---
- hosts: web_nodes
  become: yes
  vars:
    wordpress_path: /var/www/wordpress
    db_host: __your_db_private_ip__
    telegraf_influx_url: http://__your_influx_db_private_ip__:8086
    telegraf_config_path: "telegraf_apache.conf"
    apache_mod_stats_enabled: yes
    packages:
      - httpd
      - php
      - php-mysql
  roles:
    - telegraf
  tasks:
    - include_tasks: tasks/os-dependencies.yml
    - include_tasks: tasks/install-wordpress.yml
    - include_tasks: tasks/configure-apache.yml

- hosts: db_nodes
  become: yes
  tags: [db]
  vars:
    packages:
      - mariadb
      - mariadb-server
      - MySQL-python
  tasks:
    - include_tasks: tasks/os-dependencies.yml
    - include_tasks: tasks/create-wordpress-database.yml

- hosts: stats_server
  become: yes
  tags: [grafana]
  vars:
    metrics_database_name: "metrics"
    metrics_database_password: "metrics"
    metrics_database_user: "metrics"
    datasource_name: "my-influx"
    grafana_http_port: 8080
    telegraf_config_path: "telegraf_default.conf"
  roles:
    - influxdb
    - grafana
  tasks:
    - include_tasks: tasks/configure-grafana.yml
